# Site settings
title: Lambdaspace
email: info@lambdaspace.gr
description: >
    Join a vibrant comunity of hackers
baseurl: "https://kostaspakas17.github.io/githubpages-boilerplate/s"
url: "https://kostaspakas17.github.io/githubpages-boilerplate/"
twitter_username: lambdaspace
github_username:  lambdaspace

# Build settings
markdown: kramdown

include: ['_pages']
