# Site settings
title: Lambdaspace
email: info@lambdaspace.gr
description: >
    Join a vibrant comunity of hackers
baseurl: "/githubpages-boilerplate"
url: "/githubpages-boilerplate"
twitter_username: lambdaspace
github_username:  lambdaspace

# Build settings
markdown: kramdown

include: ['_pages']
